// Placeholder - this file is generated by emscripten build (scripts/build.sh)
// Run `npm run build:wasm` to generate the actual module
throw new Error('zxing_writer.wasm module not built. Run npm run build:wasm first.');
export default function MainModuleFactory(options) { return Promise.reject(new Error('not built')); }
